#ifndef MODELS_MISSION_INCLUDE_MISSION_DEFINE_H_
#define MODELS_MISSION_INCLUDE_MISSION_DEFINE_H_
typedef enum __ENUM_MISSION_EVENT_CODE {
    MISSION_EVENT_CODE_LIFTOFF = 1,
    MISSION_EVENT_CODE_S3_SEPERATION = 2,
    MISSION_EVENT_CODE_S3_CONTROL_ON = 3,
    MISSION_EVENT_CODE_S3_IGNITION = 4,
    MISSION_EVENT_FAIRING_JETTSION = 5,
    MISSION_EVENT_CODE_CONTROL_OFF = 6,
    MISSION_EVENT_CODE_MAX_NUM
} ENUM_MISSION_EVENT_CODE;
#endif  //  MODELS_MISSION_INCLUDE_MISSION_DEFINE_H_
